# Note: This workflow is disabled because it is no longer possible to archive the Discover Weekly playlist due to Spotify API changes. See the README for more details. If you fork this repo, you may need to enable it in the Actions tab
name: Archive Discover Weekly Playlist
permissions: {}
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # Run Mondays at 7:57
    - cron: "57 7 * * 1"
# Make sure that you have added these secrets in your repository settings
env:
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
  SPOTIFY_ACCESS_TOKEN: ${{ secrets.SPOTIFY_ACCESS_TOKEN }}
  SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
jobs:
  archive_discover_weekly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Python deps
        run: pip install -r requirements.txt

      # Use a helper script to get the ID of the Release Radar playlist and store it in the SPOTIFY_PLAYLIST_ID environment variable
      # We pass multiple names because the name of the playlist can vary between countries
      - name: Get playlist ID
        shell: bash
        run: >
          echo "SPOTIFY_PLAYLIST_ID=$(
            python scripts/get-playlist-id.py "$SPOTIFY_CLIENT_ID" "$SPOTIFY_CLIENT_SECRET" "$SPOTIFY_ACCESS_TOKEN" "$SPOTIFY_REFRESH_TOKEN" 'Discover Weekly' 'Découvertes de la semaine' 'Découvertes hebdomadaires' 'Descubrimiento semanal' 'Descobertas da Semana' 'Descubrimiento semanal' 'اكتشف هذا الأسبوع' 'Открытиях недели'
          )" >> $GITHUB_ENV

      # Make a copy of the Discover Weekly playlist and name it "DW - %b %e" (e.g. "DW - Jan 1")
      - name: Copy playlist
        shell: bash
        env:
          # If you want to manually set the playlist ID, specify it here and remove the above 'Get playlist ID' step
          # Note: If you don't want your playlist ID to be public, you can create a secret in your repository settings and set the env variable to ${{ secrets.SPOTIFY_PLAYLIST_ID }}
          # SPOTIFY_PLAYLIST_ID: YOUR_PLAYLIST_ID_HERE
        run: >
          python scripts/copy-playlist.py
          "$SPOTIFY_CLIENT_ID" "$SPOTIFY_CLIENT_SECRET"
          "$SPOTIFY_ACCESS_TOKEN" "$SPOTIFY_REFRESH_TOKEN"
          "$SPOTIFY_PLAYLIST_ID" "DW - %b %e"
