name: Archive Release Radar Playlist
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # Run Fridays at 7:57
    - cron: "57 7 * * 5"
# Make sure that you have added these secrets in your repository settings
env:
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
  SPOTIFY_ACCESS_TOKEN: ${{ secrets.SPOTIFY_ACCESS_TOKEN }}
  SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
jobs:
  archive_release_radar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Python deps
        run: pip install -r requirements.txt

      # Use a helper script to get the ID of the Release Radar playlist and store it in the SPOTIFY_PLAYLIST_ID environment variable
      # We pass multiple names because the name of the playlist can vary between countries
      # Note: This step is disabled because the Spotify API no longer returns information for curated playlists. You can uncomment this step if you want to try using it
      # - name: Get playlist ID
      #   shell: bash
      #   run: >
      #     echo "SPOTIFY_PLAYLIST_ID=$(
      #       python scripts/get-playlist-id.py "$SPOTIFY_CLIENT_ID" "$SPOTIFY_CLIENT_SECRET" "$SPOTIFY_ACCESS_TOKEN" "$SPOTIFY_REFRESH_TOKEN" 'Release Radar' 'Radar des sorties' 'Radar à nouveautés' 'Radar de Novedades' 'Radar de Novidades' 'Radar de novedades' 'موسيقتك الجديدة' 'Радар новинок' 'Radar premier' 'Uutuuskattaus' 'Zeneradar' '신곡 레이더' 'Nhạc mới phát hành'
      #     )" >> $GITHUB_ENV

      # Make a copy of the Release Radar playlist and name it "RR - %b %e" (e.g. "RR - Jan 1")
      - name: Copy playlist
        shell: bash
        env:
          # The ID of the playlist you want to copy
          # If you don't want your playlist ID to be public, you can create a secret in your repository settings and set the env variable to ${{ secrets.SPOTIFY_PLAYLIST_ID }}
          # Note: If you are using the above step to get the playlist ID programmatically, remove this line
          SPOTIFY_PLAYLIST_ID: 37i9dQZEVXcWj6DbkhppWk
        run: >
          python scripts/copy-playlist.py
          "$SPOTIFY_CLIENT_ID" "$SPOTIFY_CLIENT_SECRET"
          "$SPOTIFY_ACCESS_TOKEN" "$SPOTIFY_REFRESH_TOKEN"
          "$SPOTIFY_PLAYLIST_ID" "RR - %b %e"
