name: Archive Discover Weekly Playlist

on:
  schedule:
    # Run Mondays at 7:57
    - cron: "57 7 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  archive_discover_weekly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Run playlist archiver script
        shell: bash
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_ACCESS_TOKEN: ${{ secrets.SPOTIFY_ACCESS_TOKEN }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
        run: >
          python playlist-archiver-for-spotify.py
          "$SPOTIFY_CLIENT_ID" "$SPOTIFY_CLIENT_SECRET"
          "$SPOTIFY_ACCESS_TOKEN" "$SPOTIFY_REFRESH_TOKEN"
          "Discover Weekly" "DW - %b %e"
